### ISSUE TITLE
[Bug] DB initialisation fails after last update

### ISSUE THREAD

**Issue by 0xmex** [zeropingheroes/lanager#177]
**Docker image information**
```bash
[root@monkey lanager-docker-compose]# docker images zeropingheroes/lanager
REPOSITORY               TAG       IMAGE ID       CREATED        SIZE
zeropingheroes/lanager   stable    dc7f2484bf51   4 months ago   198MB
[root@monkey lanager-docker-compose]#
```

```bash
[root@monkey lanager-docker-compose]# docker ps --filter name=lanager
CONTAINER ID   IMAGE                           COMMAND                  CREATED          STATUS                    PORTS                                       NAMES
4086981dccab   mcuadros/ofelia:latest          "/usr/bin/ofelia dae…"   17 minutes ago   Up 17 minutes                                                         lanager-scheduler
fdb7eb189c47   zeropingheroes/lanager:stable   "/usr/bin/supervisor…"   17 minutes ago   Up 17 minutes (healthy)   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   lanager
924384879afc   mysql:8                         "docker-entrypoint.s…"   17 minutes ago   Up 17 minutes                                                         lanager-db
[root@monkey lanager-docker-compose]#
```

**Bug description**
After setting up LANager via Portainer I tried to set up the database with the script. This causes the db/command to fail. This also occurs when the commands are sent manually (with the `lanager` docker name of course). In my .env file both CACHE entries are standard like this:

```env
CACHE_STORE=file
CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1
```

`docker exec -it lanager php artisan migrate:fresh --force`

```bash
[2025-01-08 12:11:45] production.ERROR: Please provide a valid cache path. {"exception":"[object] (InvalidArgumentException(code: 0): Please provide a valid cache path. at /var/www/lanager/vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php:67)
[stacktrace]
#0 /var/www/lanager/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(97): Illuminate\\View\\Compilers\\Compiler->__construct()
#1 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(931): Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}()
#2 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(815): Illuminate\\Container\\Container->build()
#3 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1046): Illuminate\\Container\\Container->resolve()
#4 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(751): Illuminate\\Foundation\\Application->resolve()
#5 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1028): Illuminate\\Container\\Container->make()
#6 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(1570): Illuminate\\Foundation\\Application->make()
#7 /var/www/lanager/vendor/graham-campbell/markdown/src/MarkdownServiceProvider.php(136): Illuminate\\Container\\Container->offsetGet()
#8 /var/www/lanager/vendor/graham-campbell/markdown/src/MarkdownServiceProvider.php(53): GrahamCampbell\\Markdown\\MarkdownServiceProvider->enableBladeDirective()
#9 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): GrahamCampbell\\Markdown\\MarkdownServiceProvider->boot()
#10 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#12 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#13 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call()
#14 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1119): Illuminate\\Container\\Container->call()
#15 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1100): Illuminate\\Foundation\\Application->bootProvider()
#16 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#17 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1099): array_walk()
#18 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#19 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(316): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#20 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(473): Illuminate\\Foundation\\Application->bootstrapWith()
#21 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(195): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#22 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1203): Illuminate\\Foundation\\Console\\Kernel->handle()
#23 /var/www/lanager/artisan(13): Illuminate\\Foundation\\Application->handleCommand()
#24 {main}
"}

   InvalidArgumentException

  Please provide a valid cache path.

  at vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php:67
     63▕         $shouldCache = true,
     64▕         $compiledExtension = 'php')
     65▕     {
     66▕         if (! $cachePath) {
  ➜  67▕             throw new InvalidArgumentException('Please provide a valid cache path.');
     68▕         }
     69▕
     70▕         $this->files = $files;
     71▕         $this->cachePath = $cachePath;

      +16 vendor frames

  17  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()
      +6 vendor frames

  24  artisan:13
      Illuminate\Foundation\Application::handleCommand()

```

`docker exec -it lanager php artisan db:seed --force --class=Database\\Seeders\\DatabaseSeeder`

```bash
[2025-01-08 12:17:48] production.ERROR: Please provide a valid cache path. {"exception":"[object] (InvalidArgumentException(code: 0): Please provide a valid cache path. at /var/www/lanager/vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php:67)
[stacktrace]
#0 /var/www/lanager/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(97): Illuminate\\View\\Compilers\\Compiler->__construct()
#1 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(931): Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}()
#2 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(815): Illuminate\\Container\\Container->build()
#3 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1046): Illuminate\\Container\\Container->resolve()
#4 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(751): Illuminate\\Foundation\\Application->resolve()
#5 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1028): Illuminate\\Container\\Container->make()
#6 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(1570): Illuminate\\Foundation\\Application->make()
#7 /var/www/lanager/vendor/graham-campbell/markdown/src/MarkdownServiceProvider.php(136): Illuminate\\Container\\Container->offsetGet()
#8 /var/www/lanager/vendor/graham-campbell/markdown/src/MarkdownServiceProvider.php(53): GrahamCampbell\\Markdown\\MarkdownServiceProvider->enableBladeDirective()
#9 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): GrahamCampbell\\Markdown\\MarkdownServiceProvider->boot()
#10 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#12 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#13 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call()
#14 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1119): Illuminate\\Container\\Container->call()
#15 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1100): Illuminate\\Foundation\\Application->bootProvider()
#16 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#17 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1099): array_walk()
#18 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#19 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(316): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#20 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(473): Illuminate\\Foundation\\Application->bootstrapWith()
#21 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(195): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#22 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1203): Illuminate\\Foundation\\Console\\Kernel->handle()
#23 /var/www/lanager/artisan(13): Illuminate\\Foundation\\Application->handleCommand()
#24 {main}
"}

   InvalidArgumentException

  Please provide a valid cache path.

  at vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php:67
     63▕         $shouldCache = true,
     64▕         $compiledExtension = 'php')
     65▕     {
     66▕         if (! $cachePath) {
  ➜  67▕             throw new InvalidArgumentException('Please provide a valid cache path.');
     68▕         }
     69▕
     70▕         $this->files = $files;
     71▕         $this->cachePath = $cachePath;

      +16 vendor frames

  17  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()
      +6 vendor frames

  24  artisan:13
      Illuminate\Foundation\Application::handleCommand()

```

`docker exec -it lanager php artisan lanager:import-steam-apps-csv`

```bash
[2025-01-08 12:18:03] production.ERROR: Please provide a valid cache path. {"exception":"[object] (InvalidArgumentException(code: 0): Please provide a valid cache path. at /var/www/lanager/vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php:67)
[stacktrace]
#0 /var/www/lanager/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(97): Illuminate\\View\\Compilers\\Compiler->__construct()
#1 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(931): Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}()
#2 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(815): Illuminate\\Container\\Container->build()
#3 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1046): Illuminate\\Container\\Container->resolve()
#4 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(751): Illuminate\\Foundation\\Application->resolve()
#5 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1028): Illuminate\\Container\\Container->make()
#6 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(1570): Illuminate\\Foundation\\Application->make()
#7 /var/www/lanager/vendor/graham-campbell/markdown/src/MarkdownServiceProvider.php(136): Illuminate\\Container\\Container->offsetGet()
#8 /var/www/lanager/vendor/graham-campbell/markdown/src/MarkdownServiceProvider.php(53): GrahamCampbell\\Markdown\\MarkdownServiceProvider->enableBladeDirective()
#9 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): GrahamCampbell\\Markdown\\MarkdownServiceProvider->boot()
#10 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#12 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#13 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call()
#14 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1119): Illuminate\\Container\\Container->call()
#15 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1100): Illuminate\\Foundation\\Application->bootProvider()
#16 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#17 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1099): array_walk()
#18 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#19 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(316): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#20 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(473): Illuminate\\Foundation\\Application->bootstrapWith()
#21 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(195): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#22 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1203): Illuminate\\Foundation\\Console\\Kernel->handle()
#23 /var/www/lanager/artisan(13): Illuminate\\Foundation\\Application->handleCommand()
#24 {main}
"}

   InvalidArgumentException

  Please provide a valid cache path.

  at vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php:67
     63▕         $shouldCache = true,
     64▕         $compiledExtension = 'php')
     65▕     {
     66▕         if (! $cachePath) {
  ➜  67▕             throw new InvalidArgumentException('Please provide a valid cache path.');
     68▕         }
     69▕
     70▕         $this->files = $files;
     71▕         $this->cachePath = $cachePath;

      +16 vendor frames

  17  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()
      +6 vendor frames

  24  artisan:13
      Illuminate\Foundation\Application::handleCommand()

```

Folder structure is like this after docker container start:

```bash
[root@monkey db-data]# ls -lah
total 110M
drwxr-xr-x. 8 systemd-coredump root  4.0K Jan  8 12:25  .
drwxr-xr-x. 3 root             root  4.0K Jan  8 12:25  ..
-rw-r-----. 1 systemd-coredump input 1.9K Jan  8 12:25  4c2fb4f50a7d.err
-rw-r-----. 1 systemd-coredump input   56 Jan  8 12:25  auto.cnf
-rw-r-----. 1 systemd-coredump input 2.9M Jan  8 12:25  binlog.000001
-rw-r-----. 1 systemd-coredump input  158 Jan  8 12:25  binlog.000002
-rw-r-----. 1 systemd-coredump input   32 Jan  8 12:25  binlog.index
-rw-------. 1 systemd-coredump input 1.7K Jan  8 12:25  ca-key.pem
-rw-r--r--. 1 systemd-coredump input 1.1K Jan  8 12:25  ca.pem
-rw-r--r--. 1 systemd-coredump input 1.1K Jan  8 12:25  client-cert.pem
-rw-------. 1 systemd-coredump input 1.7K Jan  8 12:25  client-key.pem
-rw-r-----. 1 systemd-coredump input 6.0M Jan  8 12:27 '#ib_16384_0.dblwr'
-rw-r-----. 1 systemd-coredump input  14M Jan  8 12:25 '#ib_16384_1.dblwr'
-rw-r-----. 1 systemd-coredump input 5.6K Jan  8 12:25  ib_buffer_pool
-rw-r-----. 1 systemd-coredump input  12M Jan  8 12:25  ibdata1
-rw-r-----. 1 systemd-coredump input  12M Jan  8 12:25  ibtmp1
drwxr-x---. 2 systemd-coredump input 4.0K Jan  8 12:25 '#innodb_redo'
drwxr-x---. 2 systemd-coredump input 4.0K Jan  8 12:25 '#innodb_temp'
drwxr-x---. 2 systemd-coredump input 4.0K Jan  8 12:25  lanager
drwxr-x---. 2 systemd-coredump input 4.0K Jan  8 12:25  mysql
-rw-r-----. 1 systemd-coredump input  31M Jan  8 12:25  mysql.ibd
lrwxrwxrwx. 1 systemd-coredump input   27 Jan  8 12:25  mysql.sock -> /var/run/mysqld/mysqld.sock
-rw-r-----. 1 systemd-coredump input  124 Jan  8 12:25  mysql_upgrade_history
drwxr-x---. 2 systemd-coredump input 4.0K Jan  8 12:25  performance_schema
-rw-------. 1 systemd-coredump input 1.7K Jan  8 12:25  private_key.pem
-rw-r--r--. 1 systemd-coredump input  452 Jan  8 12:25  public_key.pem
-rw-r--r--. 1 systemd-coredump input 1.1K Jan  8 12:25  server-cert.pem
-rw-------. 1 systemd-coredump input 1.7K Jan  8 12:25  server-key.pem
drwxr-x---. 2 systemd-coredump input 4.0K Jan  8 12:25  sys
-rw-r-----. 1 systemd-coredump input  16M Jan  8 12:27  undo_001
-rw-r-----. 1 systemd-coredump input  16M Jan  8 12:27  undo_002
[root@monkey db-data]# ls .. -lah
total 16K
drwxr-xr-x. 3 root             root 4.0K Jan  8 12:25 .
drwxr-xr-x. 4 root             root 4.0K Jan  8 12:24 ..
drwxr-xr-x. 8 systemd-coredump root 4.0K Jan  8 12:25 db-data
-rw-r--r--. 1 root             root   44 Jan  8 12:24 mysql.cnf
[root@monkey db-data]# ls ../../app/ -lah
total 24K
drwxr-xr-x. 3 root root 4.0K Jan  8 12:25 .
drwxr-xr-x. 4 root root 4.0K Jan  8 12:24 ..
-rw-r--r--. 1 root root 1.5K Jan  8 12:24 lanager-nginx.conf
-rw-r--r--. 1 root root   64 Jan  8 12:24 lanager-php.ini
-rw-r--r--. 1 root root  327 Jan  8 12:24 lanager-php-xdebug.ini
drwxr-xr-x. 2 root root 4.0K Jan  8 12:25 laravel-storage
[root@monkey db-data]# ls ../../app/laravel-storage/ -lah
total 8.0K
drwxr-xr-x. 2 root root 4.0K Jan  8 12:25 .
drwxr-xr-x. 3 root root 4.0K Jan  8 12:25 ..
[root@monkey db-data]#
```

**Reproduction steps**
1. `git clone` the project to /opt/lanager-docker-compose
2. Delete all docker-compose files
3. Create networks in Portainer
4. Set up stack in Portainer
5. Add .env file to stack in Portainer
6. Try to deploy stack in Portainer
7. Log onto server and start `./initialise-database.sh`

**Expected behavior**
Database should get initialised

**Screenshots**
See logs proviced above

**Comment by 0xmex** [comment]
My docker-compose/stack file:

```yaml
services:

    lanager:
        image: zeropingheroes/lanager:stable
        container_name: lanager
        restart: unless-stopped
        tty: true
        ports:
            - "8080:8080"
        working_dir: /var/www/lanager
        volumes:
            - /opt/lanager-docker-compose/configs/app/laravel-storage:/var/www/lanager/storage
            - /opt/lanager-docker-compose/configs/app/lanager-php.ini:/etc/php83/conf.d/lanager-php.ini
            - /opt/lanager-docker-compose/configs/app/lanager-nginx.conf:/etc/nginx/conf.d/default.conf
        environment:
            APP_NAME: ${APP_NAME:-LANager}
            APP_ENV: ${APP_ENV:-production}
            APP_KEY: ${APP_KEY:?APP_KEY is required}
            APP_DEBUG: ${APP_DEBUG:-false}
            APP_URL: ${APP_URL:-http://localhost}
            APP_TIMEZONE: ${APP_TIMEZONE:-UTC}
            APP_LOCALE: ${APP_LOCALE:-en}
            STEAM_API_KEY: ${STEAM_API_KEY:?STEAM_API_KEY is required}
            TRUSTED_PROXIES: ${TRUSTED_PROXIES:-}
            DB_CONNECTION: ${DB_CONNECTION:-mysql}
            DB_HOST: ${DB_HOST:-db}
            DB_PORT: ${DB_PORT:-3306}
            DB_DATABASE: ${DB_DATABASE:-lanager}
            DB_USERNAME: ${DB_USERNAME:-lanager}
            DB_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD is required}
            DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?DB_ROOT_PASSWORD is required}
            CACHE_STORE: ${CACHE_DRIVER:-file}
            SESSION_DRIVER: ${SESSION_DRIVER:-database}
            SESSION_LIFETIME: ${SESSION_LIFETIME:-7200}
            LOG_CHANNEL: ${LOG_CHANNEL:-stderr}
        networks:
            - lms-net
            - mankey
        depends_on:
            - lanager-db
        labels:
            ofelia.enabled: "true"
            ofelia.job-exec.artisan-schedule-run.schedule: "@every 1m"
            ofelia.job-exec.artisan-schedule-run.command: "php /var/www/lanager/artisan schedule:run"

    lanager-scheduler:
        image: mcuadros/ofelia:latest
        container_name: lanager-scheduler
        restart: unless-stopped
        depends_on:
            - lanager
        command: daemon --docker
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - mankey

    lanager-db:
        image: mysql:8
        container_name: lanager-db
        restart: unless-stopped
        tty: true
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-lanager}
            MYSQL_USER: ${DB_USERNAME:-lanager}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - /opt/lanager-docker-compose/configs/db/db-data:/var/lib/mysql
            - /opt/lanager-docker-compose/configs/db/mysql.cnf:/etc/mysql/conf.d/lanager.cnf
        networks:
            - mankey
networks:
  lms-net:
    name: lms-net
    external: true

  mankey:
    name: mankey
    external: true
volumes:
    db-data:
        driver: local
    laravel-storage:
        driver: local
```

My .env file:

```env
APP_NAME=LANager
APP_ENV=production
APP_KEY=base64:<NO>
APP_DEBUG=false
APP_TIMEZONE=Europe/Berlin
APP_URL=https://<NO>
STEAM_API_KEY=<NO>
TRUSTED_PROXIES=<NO>
APP_LOCALE=de
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=de_DE
APP_MAINTENANCE_DRIVER=file
BCRYPT_ROUNDS=12
LOG_CHANNEL=stderr
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug
DB_CONNECTION=mysql
DB_HOST=lanager-db
DB_PORT=3306
DB_DATABASE=lanager
DB_USERNAME=lanager
DB_PASSWORD=<NO>(32 signs without specials)
DB_ROOT_PASSWORD=<NO>(other 32 signs without specials)
SESSION_DRIVER=database
SESSION_LIFETIME=7200
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null
BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database
CACHE_STORE=file
CACHE_PREFIX=
MEMCACHED_HOST=127.0.0.1
REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
MAIL_MAILER=log
MAIL_HOST=127.0.0.1
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false
VITE_APP_NAME="${APP_NAME}"
```

`lms-net` is the one NPM/the reverse proxy is located at. `mankey` is the internal network for LANager and its db/scheduler containers.
